version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    container_name: backend-s-group-app
    ports:
      - "3000:3000"
    environment:
        DB_HOST: mysqldb
    expose:
        - 3000
    volumes:
      - ./:/var/www
    depends_on:
       mysqldb: 
         condition: service_healthy
    networks:
      - example-network

  mysqldb:
    image: mysql:8.1.0
    container_name: backend-sql
    restart: 'always'
    command: --default-authentication-plugin=caching_sha2_password
    environment:
       MYSQL_USER: mysqldb    
       MYSQL_ROOT_PASSWORD :  1204
       MYSQL_DATABASE : user 
       TZ : UTC
    ports:
      - "3307:3306"
    expose:
        - 3306
        
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - example-network
    healthcheck: 
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  example-network:
    driver: bridge
